### ISSUE TITLE
Error! when I run the ~ keywords, rank, graph = wordrank_extractor.extract(texts, beta, max_iter, verbose)

### ISSUE THREAD

**Issue by directv00** [lovit/KR-WordRank#7]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data1/kt/work/KR-WordRank/krwordrank/word/_word.py", line 211, in extract
    rank, graph = self.train(docs, beta, max_iter, vocabulary, bias)
  File "/data1/kt/work/KR-WordRank/krwordrank/word/_word.py", line 319, in train
    self.scan_vocabs(docs)
  File "/data1/kt/work/KR-WordRank/krwordrank/word/_word.py", line 137, in scan_vocabs
    for token in doc.split():
AttributeError: 'ellipsis' object has no attribute 'split'
>>> keywords, rank, graph = wordrank_extractor.extract(texts, beta, max_iter, verbose)

How do I solve it?

**Comment by lovit** [comment]
I guess that input variable is wrong type. Each document in input variable docs should be str type which has implemented split function.

Your error report shows that the type of document, your input variable, is other type which has no split function. First check the variable and retry with list of str form input.
